---

- name: Install yum-utils
  become: true
  ansible.builtin.yum:
    state: present
    update_cache: true
    name:
      - yum-utils

- name: Check if docker-ce.repo repo is present
  become: true
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repos

- name: Configure repository
  become: true
  ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: not docker_ce_repos.stat.exists

- name: Docker packages installation
  become: true
  ansible.builtin.yum:
    state: present
    update_cache: true
    name:
      - containerd.io
      - docker-ce-cli
      - docker-ce
  register: centos_docker_installed
