---
- name: Docker package installation.
  become: True
  package:
    name: docker.io
    state: present
    use: auto
  register: docker_installed

- name: Start and enable docker service
  become: True
  service: 
    name: docker
    state: started
    enabled: yes
  register: docker_service_started
  when: docker_installed

- name: Add connected user to the docker group
  become: True
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
...