---
- name: Deploy docker on Ubuntu
  include_tasks: ubuntu_deploy.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name:  Deploy docker on Centos
  include_tasks: centos_deploy.yml
  when: ansible_facts['distribution'] == "CentOS"

- name: Add connected user to the docker group
  become: True
  user:
    name: ansible_user
    groups: docker
    append: yes